/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Kristjan
 */
public class Igra extends javax.swing.JFrame {

    public static int rezIgralPrvi = 0;
    public static int rezIgralDrugi = 0;
    public static String[][] tabela = new String[3][3];

    public static boolean naVrsti = IgraKdoNajBoPrvi.aliJePrijavljenPrvi;

    /**
     * Creates new form okno
     */
    public Igra() {
        initComponents();
        for (int i = 0; i < tabela.length; i++) {
            for (int j = 0; j < tabela[i].length; j++) {
                tabela[i][j] = " ";
            }
        }
        rezultat.setText(rezIgralPrvi + ":" + rezIgralDrugi);

        Igralec1Avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/" + IgraKdoNajBoPrvi.integAvatar + ".png")));
        Ime1Igralca.setText(IgraKdoNajBoPrvi.imePrijav);

        Igralec2Avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/" + NadzornaDrugiIgralec.avaDrugi + ".png")));
        Ime2Igralca.setText(NadzornaDrugiIgralec.imeDrugi);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ime1Igralca = new javax.swing.JLabel();
        Ime2Igralca = new javax.swing.JLabel();
        DvaDva = new javax.swing.JLabel();
        EnaDva = new javax.swing.JLabel();
        DvaEna = new javax.swing.JLabel();
        EnaEna = new javax.swing.JLabel();
        NicDva = new javax.swing.JLabel();
        NicEna = new javax.swing.JLabel();
        DvaNic = new javax.swing.JLabel();
        EnaNic = new javax.swing.JLabel();
        NicNic = new javax.swing.JLabel();
        Igralec1Avatar = new javax.swing.JLabel();
        Igralec2Avatar = new javax.swing.JLabel();
        rezultat = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Križci-Krožci");
        setMaximumSize(new java.awt.Dimension(450, 450));
        setMinimumSize(new java.awt.Dimension(450, 450));
        setPreferredSize(new java.awt.Dimension(450, 450));
        setResizable(false);
        getContentPane().setLayout(null);

        Ime1Igralca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Ime1Igralca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ime1Igralca.setText("1. Igralec");
        getContentPane().add(Ime1Igralca);
        Ime1Igralca.setBounds(0, 10, 190, 30);

        Ime2Igralca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Ime2Igralca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ime2Igralca.setText("2. Igralec");
        getContentPane().add(Ime2Igralca);
        Ime2Igralca.setBounds(250, 10, 180, 30);

        DvaDva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DvaDva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DvaDvaMouseClicked(evt);
            }
        });
        getContentPane().add(DvaDva);
        DvaDva.setBounds(270, 290, 90, 90);

        EnaDva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EnaDva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnaDvaMouseClicked(evt);
            }
        });
        getContentPane().add(EnaDva);
        EnaDva.setBounds(180, 290, 90, 90);

        DvaEna.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DvaEna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DvaEnaMouseClicked(evt);
            }
        });
        getContentPane().add(DvaEna);
        DvaEna.setBounds(270, 200, 90, 90);

        EnaEna.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EnaEna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnaEnaMouseClicked(evt);
            }
        });
        getContentPane().add(EnaEna);
        EnaEna.setBounds(180, 200, 90, 90);

        NicDva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NicDva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NicDvaMouseClicked(evt);
            }
        });
        getContentPane().add(NicDva);
        NicDva.setBounds(90, 290, 90, 90);

        NicEna.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NicEna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NicEnaMouseClicked(evt);
            }
        });
        getContentPane().add(NicEna);
        NicEna.setBounds(90, 200, 90, 90);

        DvaNic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DvaNic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DvaNicMouseClicked(evt);
            }
        });
        getContentPane().add(DvaNic);
        DvaNic.setBounds(270, 110, 90, 90);

        EnaNic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EnaNic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnaNicMouseClicked(evt);
            }
        });
        getContentPane().add(EnaNic);
        EnaNic.setBounds(180, 110, 90, 90);

        NicNic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NicNic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NicNicMouseClicked(evt);
            }
        });
        getContentPane().add(NicNic);
        NicNic.setBounds(90, 110, 90, 90);
        getContentPane().add(Igralec1Avatar);
        Igralec1Avatar.setBounds(60, 40, 70, 70);
        getContentPane().add(Igralec2Avatar);
        Igralec2Avatar.setBounds(310, 40, 70, 70);

        rezultat.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        rezultat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rezultat.setText("00:00");
        getContentPane().add(rezultat);
        rezultat.setBounds(140, 30, 160, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/grid.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 100, 290, 290);

        jButton1.setText("Končaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(340, 410, 90, 30);

        setSize(new java.awt.Dimension(466, 489));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void preveri() {
        if (tabela[0][0] == "x" && tabela[0][1] == "x" && tabela[0][2] == "x"
                || tabela[1][0] == "x" && tabela[1][1] == "x" && tabela[1][2] == "x"
                || tabela[2][0] == "x" && tabela[2][1] == "x" && tabela[2][2] == "x"
                || tabela[0][0] == "x" && tabela[1][0] == "x" && tabela[2][0] == "x"
                || tabela[0][1] == "x" && tabela[1][1] == "x" && tabela[2][1] == "x"
                || tabela[0][2] == "x" && tabela[1][2] == "x" && tabela[2][2] == "x"
                || tabela[0][0] == "x" && tabela[1][1] == "x" && tabela[2][2] == "x"
                || tabela[0][2] == "x" && tabela[1][1] == "x" && tabela[2][0] == "x") {
            rezIgralPrvi++;
            resetiraj();

        } else if (tabela[0][0] == "o" && tabela[0][1] == "o" && tabela[0][2] == "o"
                || tabela[1][0] == "o" && tabela[1][1] == "o" && tabela[1][2] == "o"
                || tabela[2][0] == "o" && tabela[2][1] == "o" && tabela[2][2] == "o"
                || tabela[0][0] == "o" && tabela[1][0] == "o" && tabela[2][0] == "o"
                || tabela[0][1] == "o" && tabela[1][1] == "o" && tabela[2][1] == "o"
                || tabela[0][2] == "o" && tabela[1][2] == "o" && tabela[2][2] == "o"
                || tabela[0][0] == "o" && tabela[1][1] == "o" && tabela[2][2] == "o"
                || tabela[0][2] == "o" && tabela[1][1] == "o" && tabela[2][0] == "o") {
            rezIgralDrugi++;
            resetiraj();
        } else {
            int polna = 0;
            for (int i = 0; i < tabela.length; i++) {
                for (int j = 0; j < tabela[i].length; j++) {
                    if (!tabela[i][j].equals(" ")) {
                        polna++;
                    }

                }
            }
            if (polna == 9) {
                resetiraj();
            }

        }

    }

    public void resetiraj() {

        for (int i = 0; i < tabela.length; i++) {
            for (int j = 0; j < tabela[i].length; j++) {
                tabela[i][j] = " ";
            }
        }

        NicNic.setIcon(null);
        NicEna.setIcon(null);
        NicDva.setIcon(null);
        EnaNic.setIcon(null);
        EnaEna.setIcon(null);
        EnaDva.setIcon(null);
        DvaNic.setIcon(null);
        DvaEna.setIcon(null);
        DvaDva.setIcon(null);

        rezultat.setText(rezIgralPrvi + ":" + rezIgralDrugi);
    }

    private void NicNicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NicNicMouseClicked
        // TODO add your handling code here:
        if (tabela[0][0].equals(" ")) {
            if (naVrsti) {
                NicNic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/" + IgraKdoNajBoPrvi.integAvatar + ".png")));
                naVrsti = false;
                tabela[0][0] = "x";

            } else {
                NicNic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/" + NadzornaDrugiIgralec.avaDrugi + ".png")));
                naVrsti = true;
                tabela[0][0] = "o";
            }
            preveri();
        }
    }//GEN-LAST:event_NicNicMouseClicked

    private void EnaNicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnaNicMouseClicked
        // TODO add your handling code here:
        if (tabela[0][1].equals(" ")) {
            if (naVrsti) {
                EnaNic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/" + IgraKdoNajBoPrvi.integAvatar + ".png")));
                naVrsti = false;
                tabela[0][1] = "x";
            } else {
                EnaNic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/" + NadzornaDrugiIgralec.avaDrugi + ".png")));
                naVrsti = true;
                tabela[0][1] = "o";
            }
            preveri();
        }
    }//GEN-LAST:event_EnaNicMouseClicked

    private void DvaNicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DvaNicMouseClicked
        // TODO add your handling code here:
        if (tabela[0][2].equals(" ")) {
            if (naVrsti) {
                DvaNic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/" + IgraKdoNajBoPrvi.integAvatar + ".png")));
                naVrsti = false;
                tabela[0][2] = "x";
            } else {
                DvaNic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/" + NadzornaDrugiIgralec.avaDrugi + ".png")));
                naVrsti = true;
                tabela[0][2] = "o";
            }
            preveri();
        }

    }//GEN-LAST:event_DvaNicMouseClicked

    private void NicEnaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NicEnaMouseClicked
        // TODO add your handling code here:
        if (tabela[1][0].equals(" ")) {
            if (naVrsti) {
                NicEna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/" + IgraKdoNajBoPrvi.integAvatar + ".png")));
                naVrsti = false;
                tabela[1][0] = "x";
            } else {
                NicEna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/" + NadzornaDrugiIgralec.avaDrugi + ".png")));
                naVrsti = true;
                tabela[1][0] = "o";
            }
            preveri();
        }
    }//GEN-LAST:event_NicEnaMouseClicked

    private void EnaEnaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnaEnaMouseClicked
        // TODO add your handling code here:
        if (tabela[1][1].equals(" ")) {
            if (naVrsti) {
                EnaEna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/" + IgraKdoNajBoPrvi.integAvatar + ".png")));
                naVrsti = false;
                tabela[1][1] = "x";
            } else {
                EnaEna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/" + NadzornaDrugiIgralec.avaDrugi + ".png")));
                naVrsti = true;
                tabela[1][1] = "o";
            }
            preveri();
        }
    }//GEN-LAST:event_EnaEnaMouseClicked

    private void DvaEnaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DvaEnaMouseClicked
        // TODO add your handling code here:
        if (tabela[1][2].equals(" ")) {
            if (naVrsti) {
                DvaEna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/" + IgraKdoNajBoPrvi.integAvatar + ".png")));
                naVrsti = false;
                tabela[1][2] = "x";
            } else {
                DvaEna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/" + NadzornaDrugiIgralec.avaDrugi + ".png")));
                naVrsti = true;
                tabela[1][2] = "o";
            }
            preveri();
        }
    }//GEN-LAST:event_DvaEnaMouseClicked

    private void NicDvaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NicDvaMouseClicked
        // TODO add your handling code here:
        if (tabela[2][0].equals(" ")) {
            if (naVrsti) {
                NicDva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/" + IgraKdoNajBoPrvi.integAvatar + ".png")));
                naVrsti = false;
                tabela[2][0] = "x";
            } else {
                NicDva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/" + NadzornaDrugiIgralec.avaDrugi + ".png")));
                naVrsti = true;
                tabela[2][0] = "o";
            }
            preveri();
        }
    }//GEN-LAST:event_NicDvaMouseClicked

    private void EnaDvaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnaDvaMouseClicked
        // TODO add your handling code here:
        if (tabela[2][1].equals(" ")) {
            if (naVrsti) {
                EnaDva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/" + IgraKdoNajBoPrvi.integAvatar + ".png")));
                naVrsti = false;
                tabela[2][1] = "x";
            } else {
                EnaDva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/" + NadzornaDrugiIgralec.avaDrugi + ".png")));
                naVrsti = true;
                tabela[2][1] = "o";
            }
            preveri();
        }
    }//GEN-LAST:event_EnaDvaMouseClicked

    private void DvaDvaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DvaDvaMouseClicked
        // TODO add your handling code here:
        if (tabela[2][2].equals(" ")) {
            if (naVrsti) {
                DvaDva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/" + IgraKdoNajBoPrvi.integAvatar + ".png")));
                naVrsti = false;
                tabela[2][2] = "x";
            } else {
                DvaDva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/" + NadzornaDrugiIgralec.avaDrugi + ".png")));
                naVrsti = true;
                tabela[2][2] = "o";
            }
            preveri();
        }
    }//GEN-LAST:event_DvaDvaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Zmagovalec().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Igra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Igra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Igra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Igra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Igra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DvaDva;
    private javax.swing.JLabel DvaEna;
    private javax.swing.JLabel DvaNic;
    private javax.swing.JLabel EnaDva;
    private javax.swing.JLabel EnaEna;
    private javax.swing.JLabel EnaNic;
    private javax.swing.JLabel Igralec1Avatar;
    private javax.swing.JLabel Igralec2Avatar;
    private javax.swing.JLabel Ime1Igralca;
    private javax.swing.JLabel Ime2Igralca;
    private javax.swing.JLabel NicDva;
    private javax.swing.JLabel NicEna;
    private javax.swing.JLabel NicNic;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel rezultat;
    // End of variables declaration//GEN-END:variables
}
