/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo;

import java.io.*;
import java.util.logging.*;

/**
 *
 * @author Kristjan
 */
public class IgraKdoNajBoPrvi extends javax.swing.JFrame {

    public static boolean aliJePrijavljenPrvi=true;
    public static String integAvatar;
    public static String imePrijav;
    /**
     * Creates new form Registracija
     */
    public IgraKdoNajBoPrvi() {
        initComponents();
        try {
            BufferedReader br = new BufferedReader(new FileReader("registracija.txt"));
            String vrstica;
            while (br.ready()) {
                vrstica = br.readLine();
                String[] tab = vrstica.split("¸");
                if (tab[0].equalsIgnoreCase(ZacetnoOkno.vpisanUser)) {
                    Igralec1Avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/" + tab[6] + ".png")));
                    integAvatar=tab[6];
                    imePrijav=tab[1];
                    Ime1Igralca.setText(tab[1]);
                    break;
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(IgraKdoNajBoPrvi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(IgraKdoNajBoPrvi.class.getName()).log(Level.SEVERE, null, ex);
        }
        Igralec2Avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/" + NadzornaDrugiIgralec.avaDrugi + ".png")));
        Ime2Igralca.setText(NadzornaDrugiIgralec.imeDrugi);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Igralec2Avatar = new javax.swing.JLabel();
        Igralec1Avatar = new javax.swing.JLabel();
        Ime2Igralca = new javax.swing.JLabel();
        Ime1Igralca = new javax.swing.JLabel();
        igralec2Selected = new javax.swing.JRadioButton();
        igralec1Selected = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Izbira igralca");
        setMinimumSize(new java.awt.Dimension(580, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Kdo naj bo prvi?");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 20, 200, 40);
        getContentPane().add(Igralec2Avatar);
        Igralec2Avatar.setBounds(70, 170, 100, 90);
        getContentPane().add(Igralec1Avatar);
        Igralec1Avatar.setBounds(70, 60, 100, 90);

        Ime2Igralca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Ime2Igralca.setText("2. Igralec");
        getContentPane().add(Ime2Igralca);
        Ime2Igralca.setBounds(200, 200, 350, 30);

        Ime1Igralca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Ime1Igralca.setText("1. Igralec");
        getContentPane().add(Ime1Igralca);
        Ime1Igralca.setBounds(200, 90, 360, 30);

        buttonGroup1.add(igralec2Selected);
        igralec2Selected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igralec2SelectedActionPerformed(evt);
            }
        });
        getContentPane().add(igralec2Selected);
        igralec2Selected.setBounds(20, 200, 21, 21);

        buttonGroup1.add(igralec1Selected);
        igralec1Selected.setSelected(true);
        igralec1Selected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igralec1SelectedActionPerformed(evt);
            }
        });
        getContentPane().add(igralec1Selected);
        igralec1Selected.setBounds(20, 90, 21, 21);

        jButton1.setText("Potrdi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 260, 90, 30);

        jButton2.setText("Prekliči");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(440, 260, 90, 30);

        setSize(new java.awt.Dimension(596, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Nadzorna().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Igra().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void igralec2SelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igralec2SelectedActionPerformed
        // TODO add your handling code here:
        aliJePrijavljenPrvi=false;
    }//GEN-LAST:event_igralec2SelectedActionPerformed

    private void igralec1SelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igralec1SelectedActionPerformed
        // TODO add your handling code here:
        aliJePrijavljenPrvi=true;
    }//GEN-LAST:event_igralec1SelectedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IgraKdoNajBoPrvi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IgraKdoNajBoPrvi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IgraKdoNajBoPrvi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IgraKdoNajBoPrvi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IgraKdoNajBoPrvi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Igralec1Avatar;
    private javax.swing.JLabel Igralec2Avatar;
    private javax.swing.JLabel Ime1Igralca;
    private javax.swing.JLabel Ime2Igralca;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton igralec1Selected;
    private javax.swing.JRadioButton igralec2Selected;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
