/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo;

import java.io.*;
import java.util.logging.*;

/**
 *
 * @author Kristjan
 */
public class NadzornaPodatkiOMeni extends javax.swing.JFrame {

    public static String[] tab;

    /**
     * Creates new form Registracija
     */
    public NadzornaPodatkiOMeni() {
        initComponents();

        try {
            BufferedReader br = new BufferedReader(new FileReader("registracija.txt"));
            String vrstica;
            boolean prijavljen = false;
            while (br.ready()) {
                vrstica = br.readLine();
                tab = vrstica.split("¸");
                String user = tab[0];
                if (ZacetnoOkno.vpisanUser.equalsIgnoreCase(user)) {
                    break;
                }
            }
            br.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ZacetnoOkno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ZacetnoOkno.class.getName()).log(Level.SEVERE, null, ex);
        }

        upImeLabel.setText("Uporabniško ime: " + tab[0]);
        imeLabel.setText("Ime: " + tab[1]);
        eNaslovLabel.setText("E-naslov: " + tab[3]);
        avatarLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/" + tab[6] + ".png")));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upImeLabel = new javax.swing.JLabel();
        imeLabel = new javax.swing.JLabel();
        eNaslovLabel = new javax.swing.JLabel();
        avatarInfo = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        avatarLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("O tebi");
        setMinimumSize(new java.awt.Dimension(580, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        upImeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        upImeLabel.setText("Uporabniško ime:");
        getContentPane().add(upImeLabel);
        upImeLabel.setBounds(20, 20, 540, 30);

        imeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        imeLabel.setText("Ime:");
        getContentPane().add(imeLabel);
        imeLabel.setBounds(20, 80, 540, 30);

        eNaslovLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eNaslovLabel.setText("E-naslov:");
        getContentPane().add(eNaslovLabel);
        eNaslovLabel.setBounds(20, 140, 540, 30);

        avatarInfo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        avatarInfo.setText("Avatar:");
        getContentPane().add(avatarInfo);
        avatarInfo.setBounds(20, 210, 70, 30);

        jButton3.setText("Nazaj");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(450, 250, 110, 30);
        getContentPane().add(avatarLabel);
        avatarLabel.setBounds(130, 190, 100, 90);

        setSize(new java.awt.Dimension(596, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new NadzornaKajZelis().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NadzornaPodatkiOMeni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NadzornaPodatkiOMeni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NadzornaPodatkiOMeni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NadzornaPodatkiOMeni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NadzornaPodatkiOMeni().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avatarInfo;
    private javax.swing.JLabel avatarLabel;
    private javax.swing.JLabel eNaslovLabel;
    private javax.swing.JLabel imeLabel;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel upImeLabel;
    // End of variables declaration//GEN-END:variables
}
