/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo;

import javax.swing.JOptionPane;

/**
 *
 * @author Kristjan
 */
public class NadzornaDrugiIgralec extends javax.swing.JFrame {

    public static int avaDrugi = 0;
    public static String imeDrugi = null;

    /**
     * Creates new form Registracija
     */
    public NadzornaDrugiIgralec() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton13 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton14 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton15 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jRadioButton16 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jRadioButton17 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jRadioButton20 = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jRadioButton21 = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        jRadioButton22 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jRadioButton23 = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        jRadioButton28 = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        jRadioButton29 = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        jRadioButton30 = new javax.swing.JRadioButton();
        jLabel29 = new javax.swing.JLabel();
        jRadioButton31 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Drugi igralec");
        setMinimumSize(new java.awt.Dimension(580, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Avatar 2. igralca:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(280, 10, 290, 30);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(272, 900));

        jPanel1.setMaximumSize(new java.awt.Dimension(270, 900));
        jPanel1.setMinimumSize(new java.awt.Dimension(270, 900));
        jPanel1.setPreferredSize(new java.awt.Dimension(270, 900));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/1.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 10, 64, 70);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(90, 40, 20, 21);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/2.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 10, 64, 70);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(220, 40, 20, 21);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/3.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 100, 64, 70);

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton6);
        jRadioButton6.setBounds(90, 130, 20, 21);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/4.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(150, 100, 64, 70);

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton7);
        jRadioButton7.setBounds(220, 130, 20, 21);

        buttonGroup1.add(jRadioButton12);
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton12);
        jRadioButton12.setBounds(220, 310, 20, 21);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/8.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(150, 280, 64, 70);

        buttonGroup1.add(jRadioButton13);
        jRadioButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton13);
        jRadioButton13.setBounds(90, 310, 20, 21);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/7.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 280, 64, 70);

        buttonGroup1.add(jRadioButton14);
        jRadioButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton14);
        jRadioButton14.setBounds(220, 220, 20, 21);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/6.png"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(150, 190, 64, 70);

        buttonGroup1.add(jRadioButton15);
        jRadioButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton15);
        jRadioButton15.setBounds(90, 220, 20, 21);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/5.png"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 190, 64, 70);

        buttonGroup1.add(jRadioButton16);
        jRadioButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton16);
        jRadioButton16.setBounds(220, 670, 20, 21);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/16.png"))); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(150, 640, 64, 70);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/14.png"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(150, 550, 64, 70);

        buttonGroup1.add(jRadioButton17);
        jRadioButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton17);
        jRadioButton17.setBounds(220, 580, 20, 21);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/13.png"))); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(20, 550, 64, 70);

        buttonGroup1.add(jRadioButton18);
        jRadioButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton18);
        jRadioButton18.setBounds(90, 580, 20, 21);

        buttonGroup1.add(jRadioButton19);
        jRadioButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton19);
        jRadioButton19.setBounds(90, 670, 20, 21);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/15.png"))); // NOI18N
        jPanel1.add(jLabel17);
        jLabel17.setBounds(20, 640, 64, 70);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/9.png"))); // NOI18N
        jPanel1.add(jLabel18);
        jLabel18.setBounds(20, 370, 64, 70);

        buttonGroup1.add(jRadioButton20);
        jRadioButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton20ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton20);
        jRadioButton20.setBounds(90, 400, 20, 21);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/10.png"))); // NOI18N
        jPanel1.add(jLabel19);
        jLabel19.setBounds(150, 370, 64, 70);

        buttonGroup1.add(jRadioButton21);
        jRadioButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton21ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton21);
        jRadioButton21.setBounds(220, 400, 20, 21);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/11.png"))); // NOI18N
        jPanel1.add(jLabel20);
        jLabel20.setBounds(20, 460, 64, 70);

        buttonGroup1.add(jRadioButton22);
        jRadioButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton22ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton22);
        jRadioButton22.setBounds(90, 490, 20, 21);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/12.png"))); // NOI18N
        jPanel1.add(jLabel21);
        jLabel21.setBounds(150, 460, 64, 70);

        buttonGroup1.add(jRadioButton23);
        jRadioButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton23ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton23);
        jRadioButton23.setBounds(220, 490, 20, 21);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/17.png"))); // NOI18N
        jPanel1.add(jLabel26);
        jLabel26.setBounds(20, 730, 64, 70);

        buttonGroup1.add(jRadioButton28);
        jRadioButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton28ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton28);
        jRadioButton28.setBounds(90, 760, 20, 21);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/18.png"))); // NOI18N
        jPanel1.add(jLabel27);
        jLabel27.setBounds(150, 730, 64, 70);

        buttonGroup1.add(jRadioButton29);
        jRadioButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton29ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton29);
        jRadioButton29.setBounds(220, 760, 20, 21);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/19.png"))); // NOI18N
        jPanel1.add(jLabel28);
        jLabel28.setBounds(20, 820, 64, 70);

        buttonGroup1.add(jRadioButton30);
        jRadioButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton30ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton30);
        jRadioButton30.setBounds(90, 850, 20, 21);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/avatarji/20.png"))); // NOI18N
        jPanel1.add(jLabel29);
        jLabel29.setBounds(150, 820, 64, 70);

        buttonGroup1.add(jRadioButton31);
        jRadioButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton31ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton31);
        jRadioButton31.setBounds(220, 850, 20, 21);

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(270, 50, 300, 200);

        jButton2.setText("Potrdi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(50, 180, 160, 30);

        jButton3.setText("Prekliči");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(370, 260, 110, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Ime 2. igralca:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 50, 170, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(40, 90, 180, 30);

        setSize(new java.awt.Dimension(596, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Nadzorna().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        imeDrugi = jTextField1.getText();
        if (avaDrugi == 0) {
            JOptionPane.showMessageDialog(null, "Prosim, izberi avatar!");
        } else if (imeDrugi.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Prosim, vpiši ime!");
        } else if (Nadzorna.avatarPrijavljen == avaDrugi) {
            JOptionPane.showMessageDialog(null, "Prosim, izberi drugačnega avatarja!");
        } else {
            new IgraKdoNajBoPrvi().setVisible(true);
            this.dispose();

        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        avaDrugi = 1;
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        avaDrugi = 2;
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        avaDrugi = 3;
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        avaDrugi = 4;
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton15ActionPerformed
        avaDrugi = 5;
    }//GEN-LAST:event_jRadioButton15ActionPerformed

    private void jRadioButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton14ActionPerformed
        avaDrugi = 6;
    }//GEN-LAST:event_jRadioButton14ActionPerformed

    private void jRadioButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton13ActionPerformed
        avaDrugi = 7;
    }//GEN-LAST:event_jRadioButton13ActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        avaDrugi = 8;
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    private void jRadioButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton20ActionPerformed
        avaDrugi = 9;
    }//GEN-LAST:event_jRadioButton20ActionPerformed

    private void jRadioButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton21ActionPerformed
        avaDrugi = 10;
    }//GEN-LAST:event_jRadioButton21ActionPerformed

    private void jRadioButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton22ActionPerformed
        avaDrugi = 11;
    }//GEN-LAST:event_jRadioButton22ActionPerformed

    private void jRadioButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton23ActionPerformed
        avaDrugi = 12;
    }//GEN-LAST:event_jRadioButton23ActionPerformed

    private void jRadioButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton18ActionPerformed
        avaDrugi = 13;
    }//GEN-LAST:event_jRadioButton18ActionPerformed

    private void jRadioButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton17ActionPerformed
        avaDrugi = 14;
    }//GEN-LAST:event_jRadioButton17ActionPerformed

    private void jRadioButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton19ActionPerformed
        avaDrugi = 15;
    }//GEN-LAST:event_jRadioButton19ActionPerformed

    private void jRadioButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton16ActionPerformed
        avaDrugi = 16;
    }//GEN-LAST:event_jRadioButton16ActionPerformed

    private void jRadioButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton28ActionPerformed
        avaDrugi = 17;
    }//GEN-LAST:event_jRadioButton28ActionPerformed

    private void jRadioButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton29ActionPerformed
        avaDrugi = 18;
    }//GEN-LAST:event_jRadioButton29ActionPerformed

    private void jRadioButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton30ActionPerformed
        avaDrugi = 19;
    }//GEN-LAST:event_jRadioButton30ActionPerformed

    private void jRadioButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton31ActionPerformed
        avaDrugi = 20;
    }//GEN-LAST:event_jRadioButton31ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NadzornaDrugiIgralec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NadzornaDrugiIgralec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NadzornaDrugiIgralec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NadzornaDrugiIgralec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NadzornaDrugiIgralec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
