/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo;

import java.io.*;
import java.util.logging.*;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Kristjan
 */
public class PozabljenoGeslo extends javax.swing.JFrame {

    public static String vDatVpras;
    public static String vDatOdg;
    public static String upIme;

    /**
     * Creates new form Registracija
     */
    public PozabljenoGeslo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pozUpIme = new javax.swing.JTextField();
        eNaslov = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pozabljeno geslo");
        setMinimumSize(new java.awt.Dimension(580, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("E-naslov:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 110, 170, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Uporabniško ime:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 40, 170, 30);

        pozUpIme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pozUpImeActionPerformed(evt);
            }
        });
        getContentPane().add(pozUpIme);
        pozUpIme.setBounds(220, 40, 120, 30);
        getContentPane().add(eNaslov);
        eNaslov.setBounds(220, 110, 200, 30);

        jButton3.setText("Nazaj");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(450, 250, 110, 30);

        jButton2.setText("Preveri");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 190, 110, 30);

        setSize(new java.awt.Dimension(596, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new ZacetnoOkno().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    public static int cekirajPozabGeslo(String upIme, String mail) {
        if (upIme.isEmpty()) {
            return 1;
        }
        if (upIme.contains(" ")) {
            return 2;
        }
        if (upIme.contains("¸")) {
            return 3;
        }
        if (mail.isEmpty()) {
            return 4;
        }
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."
                + "[a-zA-Z0-9_+&*-]+)*@"
                + "(?:[a-zA-Z0-9-]+\\.)+[a-z"
                + "A-Z]{2,7}$";

        Pattern pat = Pattern.compile(emailRegex);
        if (!pat.matcher(mail).matches()) {
            return 5;
        }

        try {
            BufferedReader br = new BufferedReader(new FileReader("registracija.txt"));
            String vrstica;
            boolean prev = true;
            while (br.ready()) {
                vrstica = br.readLine();
                String[] tab = vrstica.split("¸");
                String user = tab[0];
                String userMail = tab[3];
                if (user.equals(upIme) && userMail.equals(mail)) {
                    prev = false;
                    vDatVpras = tab[4];
                    vDatOdg = tab[5];
                    break;
                } else {
                    prev = true;
                }
            }
            br.close();
            if (prev) {
                return 6;
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(ZacetnoOkno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ZacetnoOkno.class.getName()).log(Level.SEVERE, null, ex);
        }

        return 0;
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        upIme = pozUpIme.getText();
        String mail = eNaslov.getText();
        int vrni = cekirajPozabGeslo(upIme, mail);

        switch (vrni) {
            case 1:
                JOptionPane.showMessageDialog(null, "Uporabniško ime ne sme biti prazno!");
                break;
            case 2:
                JOptionPane.showMessageDialog(null, "Uporabniško ime ne sme vsebovati presledka!");
                break;
            case 3:
                JOptionPane.showMessageDialog(null, "Uporabil si ilegalen simbol \"¸\"!");
                break;
            case 4:
                JOptionPane.showMessageDialog(null, "E-naslov ne sme biti prazen!");
                break;
            case 5:
                JOptionPane.showMessageDialog(null, "Format E-naslova ni pravilen!");
                break;
            case 6:
                JOptionPane.showMessageDialog(null, "Kombinacija uporabniškega imena, ter E-naslova ni bila najdena!");
                break;

            default:
                new PozabljenoGesloNas().setVisible(true);
                this.dispose();

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void pozUpImeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pozUpImeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pozUpImeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PozabljenoGeslo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PozabljenoGeslo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PozabljenoGeslo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PozabljenoGeslo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PozabljenoGeslo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eNaslov;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField pozUpIme;
    // End of variables declaration//GEN-END:variables
}
