/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo;

import java.io.*;
import java.util.logging.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Kristjan
 */
public class PozabljenoGesloSprememba extends javax.swing.JFrame {

    /**
     * Creates new form Registracija
     */
    public PozabljenoGesloSprememba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        logGeslo = new javax.swing.JPasswordField();
        logGeslo1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pozabljeno geslo");
        setMinimumSize(new java.awt.Dimension(580, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton2.setText("Spremeni geslo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(190, 220, 160, 30);

        jButton3.setText("Prekliči");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(450, 250, 110, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Novo geslo:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 30, 190, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Potrdi novo geslo:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 120, 190, 30);
        getContentPane().add(logGeslo);
        logGeslo.setBounds(260, 30, 120, 30);
        getContentPane().add(logGeslo1);
        logGeslo1.setBounds(260, 120, 120, 30);

        setSize(new java.awt.Dimension(596, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (NadzornaSpremeni.hocesSpremenit) {
            new NadzornaSpremeni().setVisible(true);
            NadzornaSpremeni.hocesSpremenit = false;
            this.dispose();
        } else {
            new ZacetnoOkno().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String nGeslo = logGeslo.getText();
        String nGesloPonovi = logGeslo1.getText();
        if (!nGeslo.equals(nGesloPonovi)) {
            JOptionPane.showMessageDialog(null, "Gesli se ne ujemata!");
        } else if (nGeslo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Geslo ne sme biti prazno!");
        } else if (nGeslo.contains("¸")) {
            JOptionPane.showMessageDialog(null, "Uporabil si ilegalen simbol \"¸\"!");
        } else {
            try {
                BufferedReader br = new BufferedReader(new FileReader("registracija.txt"));
                StringBuilder sBuild = new StringBuilder();
                String vrstica;
                while (br.ready()) {
                    vrstica = br.readLine();
                    String[] tab = vrstica.split("¸");
                    String user = tab[0];
                    if (NadzornaSpremeni.hocesSpremenit) {
                        PozabljenoGeslo.upIme = ZacetnoOkno.vpisanUser;
                    }
                    if (user.equals(PozabljenoGeslo.upIme)) {
                        String posodobljeno = tab[0] + "¸" + tab[1] + "¸" + nGeslo + "¸" + tab[3] + "¸" + tab[4] + "¸" + tab[5] + "¸" + tab[6];
                        sBuild.append(posodobljeno);
                        sBuild.append("\n");

                    } else {
                        sBuild.append(vrstica);
                        sBuild.append("\n");
                    }

                }
                FileWriter file = new FileWriter("registracija.txt");
                BufferedWriter bw = new BufferedWriter(file);
                bw.write(sBuild.toString());

                bw.close();
                br.close();

                JOptionPane.showMessageDialog(null, "Geslo je spremenjeno!");
                if (NadzornaSpremeni.hocesSpremenit) {
                    new NadzornaSpremeni().setVisible(true);
                    NadzornaSpremeni.hocesSpremenit = false;
                    ZacetnoOkno.vpisanoGeslo = nGeslo;
                    this.dispose();
                } else {
                    new ZacetnoOkno().setVisible(true);
                    this.dispose();
                }

            } catch (FileNotFoundException ex) {
                Logger.getLogger(PozabljenoGesloSprememba.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(PozabljenoGesloSprememba.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PozabljenoGesloSprememba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PozabljenoGesloSprememba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PozabljenoGesloSprememba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PozabljenoGesloSprememba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PozabljenoGesloSprememba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField logGeslo;
    private javax.swing.JPasswordField logGeslo1;
    // End of variables declaration//GEN-END:variables
}
