/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo;

import java.io.*;
import java.util.logging.*;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Kristjan
 */
public class Registracija extends javax.swing.JFrame {

    public static String upIme = "";
    public static String Ime = "";
    public static String geslo = "";
    public static String ponGeslo = "";
    public static String mail = "";

    /**
     * Creates new form Registracija
     */
    public Registracija() {
        initComponents();
    }

    public static int cekiraj(String upIme, String Ime, String geslo, String ponGeslo, String mail) {
        if (upIme.isEmpty()) {
            return 1;
        }
        if (upIme.contains(" ")) {
            return -1;
        }

        try {
            BufferedReader br = new BufferedReader(new FileReader("registracija.txt"));
            String vrstica;
            while (br.ready()) {
                vrstica = br.readLine();
                String[] tab = vrstica.split("¸");
                String user = tab[0];
                if (user.equalsIgnoreCase(upIme)) {
                    return 2;
                }
            }
            br.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ZacetnoOkno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ZacetnoOkno.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (Ime.isEmpty()) {
            return 3;
        }

        if (geslo.isEmpty()) {
            return 4;
        }

        if (!geslo.equals(ponGeslo)) {
            return 5;
        }

        if (mail.isEmpty()) {
            return 6;
        }
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."
                + "[a-zA-Z0-9_+&*-]+)*@"
                + "(?:[a-zA-Z0-9-]+\\.)+[a-z"
                + "A-Z]{2,7}$";

        Pattern pat = Pattern.compile(emailRegex);
        if (!pat.matcher(mail).matches()) {
            return 7;
        }
        if (upIme.contains("¸") || Ime.contains("¸") || geslo.contains("¸")) {
            return 8;
        }
        if (upIme.length() > 22) {
            return 9;
        }

        return 0;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        regUpIme = new javax.swing.JTextField();
        regIme = new javax.swing.JTextField();
        regGeslo = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        eNaslov = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        regGeslo1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registracija");
        setMaximumSize(new java.awt.Dimension(580, 300));
        setMinimumSize(new java.awt.Dimension(580, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton2.setText("Nadaljuj z registracijo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(390, 80, 160, 30);
        getContentPane().add(regUpIme);
        regUpIme.setBounds(220, 20, 120, 30);

        regIme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regImeActionPerformed(evt);
            }
        });
        getContentPane().add(regIme);
        regIme.setBounds(220, 70, 120, 30);

        regGeslo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regGesloActionPerformed(evt);
            }
        });
        getContentPane().add(regGeslo);
        regGeslo.setBounds(220, 120, 120, 30);

        jButton3.setText("Nazaj");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(450, 250, 110, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Uporabniško ime:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 20, 170, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Geslo:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 120, 170, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Ime:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 70, 170, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("E-naslov:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 220, 170, 30);

        eNaslov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eNaslovActionPerformed(evt);
            }
        });
        getContentPane().add(eNaslov);
        eNaslov.setBounds(220, 220, 200, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Ponovno geslo:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 170, 170, 30);

        regGeslo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regGeslo1ActionPerformed(evt);
            }
        });
        getContentPane().add(regGeslo1);
        regGeslo1.setBounds(220, 170, 120, 30);

        setSize(new java.awt.Dimension(596, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        upIme = regUpIme.getText();
        Ime = regIme.getText();
        geslo = regGeslo.getText();
        ponGeslo = regGeslo1.getText();
        mail = eNaslov.getText();
        int aJeOK = cekiraj(upIme, Ime, geslo, ponGeslo, mail);

        switch (aJeOK) {

            case 1:
                JOptionPane.showMessageDialog(null, "Uporabniško ime ne sme biti prazno!");
                break;
            case -1:
                JOptionPane.showMessageDialog(null, "Uporabniško ime ne sme vsebovati presledka!");
                break;
            case 2:
                JOptionPane.showMessageDialog(null, "Uporabniško ime je že zasedeno!");
                break;
            case 3:
                JOptionPane.showMessageDialog(null, "Ime ne sme biti prazno!");
                break;
            case 4:
                JOptionPane.showMessageDialog(null, "Geslo ne sme biti prazno!");
                break;
            case 5:
                JOptionPane.showMessageDialog(null, "Gesli se ne ujemata!");
                break;
            case 6:
                JOptionPane.showMessageDialog(null, "E-naslov ne sme biti prazen!");
                break;
            case 7:
                JOptionPane.showMessageDialog(null, "Format E-naslova ni pravilen!");
                break;
            case 8:
                JOptionPane.showMessageDialog(null, "Uporabil si ilegalen simbol \"¸\"!");
                break;
            case 9:
                JOptionPane.showMessageDialog(null, "Uporabniško ime mora biti krajše!");
                break;
            default:
                new RegistracijaNas().setVisible(true);
                this.dispose();

        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void regImeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regImeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regImeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new ZacetnoOkno().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void regGesloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regGesloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regGesloActionPerformed

    private void eNaslovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eNaslovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eNaslovActionPerformed

    private void regGeslo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regGeslo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regGeslo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registracija().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eNaslov;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField regGeslo;
    private javax.swing.JPasswordField regGeslo1;
    private javax.swing.JTextField regIme;
    private javax.swing.JTextField regUpIme;
    // End of variables declaration//GEN-END:variables
}
